### ISSUE TITLE
Core->Setup: No Overdrafts in Invariants results in error

### ISSUE THREAD

**Issue by Svintooo** [hwayne/learntla-v2#15]
### File
docs/core/setup.rst

### Problem
Adding "No Overdrafts" as an Invariant results in an error when trying to run the model.

### Error
```
***Parse Error***
Was expecting "=== or more Module body"
Encountered "Overdrafts" in Invariants at line 1 and token "No"

Residual stack trace follows:
Module definition starting at line 1, column 1.
```

### Comments
I am complete beginner. I have never heard of TLA or touched it before.
I redid the guide from scratch an extra time just to make sure I didn't do anything wrong. But I got the same error both times.

### My Setup
OS: Windows 10 (running in a VM)
Cores: 1
RAM: 4G
Java: Version 8 Update 333 (build 1.8.0_333-b02)
Toolbox: https://github.com/tlaplus/tlaplus/releases/tag/v1.8.0
Exec: Unpacked TLAToolbox-1.8.0-win32.win32.x86_64.zip and ran toolbox.exe

**Comment by hwayne** [comment]
Does `NoOverdrafts` work without a space?

**Comment by Svintooo** [comment]
Using `NoOverdrafts` (without a space) seems to resolve the problem. I am now able to continue.
Thank you!

**Comment by hwayne** [comment]
Sounds like something I need to fix!

**Comment by npalladium** [comment]
Just came here to file this issue/open a tiny PR to fix the space. :P

**Comment by hwayne** [comment]
Merg'd!
