### ISSUE TITLE
Clarify the 8 existing TLA+ types

### ISSUE THREAD

**Issue by jmg-duarte** [hwayne/learntla-v2#23]
[Values](https://learntla.com/core/operators.html#values) starts with:
> TLA+ is an “untyped” language, due to its roots in mathematics. In practice, the model checker recognizes four primitive types and four advanced ones.
But these types are not _explicitly_ (or at least not explicitly enough) demonstrated to the reader.

To address this, I think a simple list with links to the relevant part of the book would suffice.

**Comment by hwayne** [comment]
So like take the note below and expand it into a list with all eight?

**Comment by jmg-duarte** [comment]
Yes!

**Comment by hwayne** [comment]
Yeah I keep procrastinating this, srry

**Comment by jmg-duarte** [comment]
No problem, you don't owe people your work, you're giving it away for free! If you provide me with a link to a more complete resource I can help you with a draft!

**Comment by hwayne** [comment]
Fixed
