### ISSUE TITLE
How to make a scratch file?

### ISSUE THREAD

**Issue by louy2** [hwayne/learntla-v2#25]
In the section Setup > Making a Scratchfile, the paragraph only mentions

> To do that, I have a separate file I call “Scratch”

Yet how to create this separate file is not mentioned. I started looking for "New File" without success.

There is also a strong relation that a file is a module, so I started looking for "New Module", which I found, but it not mentioned in the guide makes me unsure what to make of it.

Finally I remember that the guide until this point only mentioned creating spec, and creating a separate scratch spec works.

For the scratch spec, the screenshot shows the file name to be lowercase "scratch", but the listed code has titlecase `MODULE Scratch` which led to an error.

For the scratch model, the screenshot shows the Value box to the bottom, but the text reads "the output of `Eval` will be put on the box to the right."

**Comment by hwayne** [comment]
I'll check through everything this week.

**Comment by jmg-duarte** [comment]
@louy2 So you're not left hanging, here's my textual guide:

- On the file manager, right-click for "New specification"
- Follow the file wizard to the end
- In your newly created spec, add the code as described in the book
- After writing the spec, ensure that it parses
- Create a new model by right-clicking "Models" 
- Follow the rest of the guide

I know this isn't much of a guide, but hope it helps!

**Comment by hwayne** [comment]
Fixed, will push soon!
