### ISSUE TITLE
Navigation structure

### ISSUE THREAD

**Issue by th** [hwayne/learntla-v2#3]
index.rst:

Rethink when things have settled down: structure apparent to reader in sidebar is "Learn", "Examples" and "Reference", where "Core" and "Topics" are under "Learn" today.

You said: "That's intentional, though it may be a bad idea"

I reply: I really think it's a bad idea :-)

**Comment by hwayne** [comment]
Why do you think it's a bad idea?

**Comment by hwayne** [comment]
Feel free to reopen with your response!
