### ISSUE TITLE
Clarify model for the threads example

### ISSUE THREAD

**Issue by ramz-san** [hwayne/learntla-v2#30]
For the threads example in the concurrency section there is no indication on how assign the constant NULL when running the model after adding the lock. I think it might be a good idea to explicitly state how to run the model.

If I understand correctly both assigning a model variable or an ordinary assignment of, say, -1 would work equally well in this case, but the model variable would be preferable. If that's the case it might also be a good idea to explain the difference between both possibilities.

**Comment by hwayne** [comment]
I'll make some updates!
