### ISSUE TITLE
On the size of `SUBSET ClockType`

### ISSUE THREAD

**Issue by wchargin** [hwayne/learntla-v2#35]
The ["Operators and Values" page][1] says:

> As a quick sanity check, run `Cardinality(ClockType)` [...]. You should see it has 86400 elements. [...]
>
> Finally, we can get all subsets of a set with `SUBSET S`. `SUBSET ClockType` will be all the sets containing a bunch of clock values… all 7,464,960,000 of them.

[1]: https://www.learntla.com/core/operators.html#sets-of-values

The 7-billion-ish figure is 86400^2, but shouldn't the actual
cardinality of `SUBSET S` be the vastly larger 2^86400?

For example, if I ask my scratchfile to evaluate the size of `SUBSET S`
when `S` has 6 elements, it properly reports 64 (= 2^6):

```pluscal
SixType == (0..1) \X (0..2)

>>> <<Cardinality(SixType), Cardinality(SUBSET SixType)>>
<<6, 64>>
```

I also can't quite reproduce the behavior of the `#million` footnote
with a fresh install of TLAToolbox-1.8.0 on Linux. Specifically,
`Cardinality(SUBSET (1..30))` happily evaluates to 1073741824, while
attempting to compute `Cardinality(SUBSET (1..31))` fails with "Overflow
when computing the number of elements". Maybe this is out of date?

(would generally send a PR here but I'm brand new to TLA+ so rather
unconfident with which changes to suggest; thanks for all your work!)

**Comment by hwayne** [comment]
You are 100% right, it'd be 2^86400. Now just gotta figure out how many digits that has... Think 2^10 = 10^3 is a good enough approximation? :D

Million footnote might be out of date.

**Comment by hwayne** [comment]
If you do `CHOOSE x in (SUBSET 1..30): TRUE`, does that work?

**Comment by wchargin** [comment]
> You are 100% right, it'd be 2^86400. Now just gotta figure out how many digits that has... Think 2^10 = 10^3 is a good enough approximation? :D

Think it has `1 + floor(86400 / log_2(10)) = 26008` decimal digits, yes?
Seems fine to round that basically however you want. :-)

> If you do `CHOOSE x in (SUBSET 1..30): TRUE`, does that work?

Yeah, `CHOOSE s \in (SUBSET (1..30)): TRUE` evaluates to `{}` for me,
and even `CHOOSE s \in (SUBSET (1..30)): Cardinality(s) = 30` took five
minutes but finally evaluated to `(1..30)`.

**Comment by hwayne** [comment]
Ta!

**Comment by hwayne** [comment]
I'll try to update this on Friday

**Comment by hwayne** [comment]
Wow I'm late
