### ISSUE TITLE
Wording of "new" types

### ISSUE THREAD

**Issue by th** [hwayne/learntla-v2#4]
operators.rst:

> If you want to get on ahead, the new types we are not talking about are `model values <model_value>`, `structs <struct>`, and
> `functions <function>`. Yes, operators and functions are different things. 

Sorry, this had me stumble, because I wasn't sure what “new” refers to here. I surmised that it might be the ones not covered now, but the wording seemed strange and it had me count in the right sidebar if 3 types were missing from the 4+4. Which wasn't easy, because the structure in the sidebar isn't meant to support this counting. Maybe just leave out the “new”?

**Comment by hwayne** [comment]
Updated!
