### ISSUE TITLE
Question about > vs. = in example.

### ISSUE THREAD

**Issue by th** [hwayne/learntla-v2#5]
operators.rst:

> {t \in ClockType: t[2] = 29 /\ t[3] = 0}

Why not t[2] = 30? We're 1-indexing, right?

At first I misunderstood that as “all the times in the second half of the hour” and wondered why there isn't a > anywhere. Maybe check if others misread it similarly?

**Comment by hwayne** [comment]
This is 0-indexing (minutes go from 0 to 59). will fix.

**Comment by hwayne** [comment]
Fixed
