### ISSUE TITLE
syntax highlighting bug in Structured Data part

### ISSUE THREAD

**Issue by acud** [hwayne/learntla-v2#62]
In the tip section within `Function sets`:
```
A function set of form [A -> B] will have 
 elements in it. If there were two tasks and three CPUs, that would be :math`(2^3)^2 = 64` possible functions.
```
Here, `:math` should be changed to whatever should yield the right result or simply be removed in favor of the usual syntax highlighting

**Comment by hwayne** [comment]
Should be `:math:`, not `:math`
